<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 13/04/16
 * Time: 20:36
 */
/** @var AccueilController $_accueil */
$_accueil = $this;
?>
<div class="row col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
    <h3>Bienvienue sur le site du tournoi inter club loisir de Badminton Vendéen édition 2016/2017</h3>
    <!--<p></p>-->
    <ul>
        <li><a href="Matchs">Journées et feuilles de match</a></li>
        <li><a href="Classement">Classement</a></li>
    </ul>
</div>