<?php
/**
 * User: corpas
 * Date: 08/05/16
 * Time: 21:08
 */
/** @var MatchsController $_match */
$_match = $this;
$_post = $_match->getPost();
$_utilisateur = Access::getInstance()->getCurrentUser();
$defaultTeam = $_utilisateur->getAttribute('equipe_default');
$_matchCollection = $_match->getAllMatch();
$idMatch = $_post['matchDetail'];
$match = $_matchCollection->loadById($idMatch);
$_simpleCollection = new SimpleCollection();
$_doubleCollection = new DoubleCollection();
$_allSimple = $_simpleCollection->load(["match" => ["=", $idMatch]]);
$_allDouble = $_doubleCollection->load(["match" => ["=", $idMatch]]);
$equipe = new EquipeCollection();
$joueurs_1 = $_match->getListJoueurByTeam($match->getAttribute('equipe_id_1'));
$joueurs_2 = $_match->getListJoueurByTeam($match->getAttribute('equipe_id_2'));
?>

<div style="display: none;">
    <div class="team1">
        <select title="team1">
            <option value="0"></option>
        <?php /** @var JoueurModel $joueur */
        foreach ($joueurs_1 as $joueur) : ?>
            <option value="<?php echo $joueur->getAttribute('id') ?>"><?php echo $joueur->getAttribute('name') ?></option>
        <?php endforeach; ?>
        </select>
    </div>
    <div class="team2">
        <select title="team2">
            <option value="0"></option>
            <?php /** @var JoueurModel $joueur */
            foreach ($joueurs_2 as $joueur) : ?>
                <option value="<?php echo $joueur->getAttribute('id') ?>"><?php echo $joueur->getAttribute('name') ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>

<div>
    <form class="form-horizontal" method="post" action="saveDetail">
        <input type="hidden" name="match" value="<?php echo $idMatch ?>">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1" id="simplediv">
                <div class="row" align="center">
                    <h1><?php echo $equipe->loadById($match->getAttribute('equipe_id_1'))->getAttribute('name') ?> <span id="scoreE1">0</span> - <span id="scoreE2">0</span> <?php echo $equipe->loadById($match->getAttribute('equipe_id_2'))->getAttribute('name') ?></h1>
                </div>
                <?php if($_utilisateur != NULL && ($equipe->loadById($match->getAttribute('equipe_id_1'))->getAttribute('id') == $defaultTeam)): ?>
                <div class="row marginContentTab">
                    <button class="btn btn-info mrg" type="submit">ENREGISTRER</button>
                </div>
                <?php endif; ?>
                <h1>Simples <button class="btn btn-default green" type="button" id="addSimple">+</button></h1>
                <div class="row hidden-sm hidden-md" align="center" id="labels">
                    <label class="col-lg-2" for="joueur1">Joueur (<?php echo $equipe->loadById($match->getAttribute('equipe_id_1'))->getAttribute('name')?>)</label>
                    <label class="col-lg-2" for="joueur2">Joueur (<?php echo $equipe->loadById($match->getAttribute('equipe_id_2'))->getAttribute('name')?>)</label>
                    <label class="col-lg-2" for="score1_1">Match 1</label>
                    <label class="col-lg-2" for="score2">Match 2</label>
                    <label class="col-lg-2" for="score3">Match 3</label>
                </div>
                <!--                DEBUT MATCH SIMPLE-->
                <?php $i=0;
                /** @var SimpleModel $simple */
                foreach ($_allSimple as $simple):
                    $i++?>
                    <div style="margin-bottom: 4px;" class="row" align="center" id="simple[<?php echo $i ?>]">
                        <div class="col-lg-2 col-sm-5">
                            <select id="joueurS1[<?php echo $i ?>]" name="joueurS[<?php echo $i ?>][joueur_1]" class="form-control form-control2 first" title="joueur">
                                <option value="0"></option>
                                <?php /** @var JoueurModel $joueur */
                                foreach ($joueurs_1 as $joueur) : ?>
                                <option value="<?php echo $joueur->getAttribute('id') ?>" <?php echo $simple->getAttribute('joueur_1')==$joueur->getAttribute('id')?'selected':'' ?>><?php echo $joueur->getAttribute('name') ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-lg-2 col-sm-5">
                            <select id="joueurS2[<?php echo $i ?>]" name="joueurS[<?php echo $i ?>][joueur_2]" class="form-control form-control2 second" title="joueur">
                                <option value="0"></option>
                                <?php /** @var JoueurModel $joueur */
                                foreach ($joueurs_2 as $joueur) : ?>
                                    <option value="<?php echo $joueur->getAttribute('id') ?>" <?php echo $simple->getAttribute('joueur_2')==$joueur->getAttribute('id')?'selected':'' ?>><?php echo $joueur->getAttribute('name') ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-lg-2 col-sm-10">
                            <input class="form-control first" id="scoreS1_1[<?php echo $i ?>]" type="number" value="<?php echo $simple->getAttribute('score_1_1') ?>" name="scoreS[<?php echo $i ?>][match_1_1]">
                            <input class="form-control second" id="scoreS1_2[<?php echo $i ?>]" type="number" value="<?php echo $simple->getAttribute('score_1_2') ?>" name="scoreS[<?php echo $i ?>][match_1_2]">
                        </div>
                        <div class="col-lg-2 col-sm-10">
                            <input class="form-control btn-xs first" id="scoreS2_1[<?php echo $i ?>]" type="number" value="<?php echo $simple->getAttribute('score_2_1') ?>" name="scoreS[<?php echo $i ?>][match_2_1]">
                            <input class="form-control btn-xs second" id="scoreS2_2[<?php echo $i ?>]" type="number" value="<?php echo $simple->getAttribute('score_2_2') ?>" name="scoreS[<?php echo $i ?>][match_2_2]">
                        </div>
                        <div class="col-lg-2 col-sm-10">
                            <input class="form-control btn-xs first" id="scoreS3_1[<?php echo $i ?>]" type="number" value="<?php echo $simple->getAttribute('score_3_1') ?>" name="scoreS[<?php echo $i ?>][match_3_1]">
                            <input class="form-control btn-xs second" id="scoreS3_2[<?php echo $i ?>]" type="number" value="<?php echo $simple->getAttribute('score_3_2') ?>" name="scoreS[<?php echo $i ?>][match_3_2]">
                        </div>
                        <div class="col-lg-1">
                            <p class="score_binaire"></p>
                        </div>
                        <div class="col-lg-1">
                            <button class="btn btn-default red" type="button" data-idS="<?php echo $i ?>">-</button>
                        </div>
                        <input type="hidden" name="databaseIdS[<?php echo $i ?>]" value="<?php echo $simple->getAttribute('id')?>"> <!--// AJOUTER AU JS-->
                    </div>
                <?php endforeach; ?>
                <!--                FIN MATCH SIMPLE-->
            </div>
            <div style="margin-bottom: 4px;" class="col-lg-10 col-lg-offset-1" id="doublediv">
                <h1>Doubles <button class="btn btn-default green" type="button" id="addDouble">+</button></h1>
                <div class="row hidden-sm hidden-md" align="center" id="labelsD">
                    <label class="col-lg-2" for="joueur1">Joueurs (<?php echo $equipe->loadById($match->getAttribute('equipe_id_1'))->getAttribute('name')?>)</label>
                    <label class="col-lg-2" for="joueur2">Joueurs (<?php echo $equipe->loadById($match->getAttribute('equipe_id_2'))->getAttribute('name')?>)</label>
                    <label class="col-lg-2" for="score1_1">Match 1</label>
                    <label class="col-lg-2" for="score2">Match 2</label>
                    <label class="col-lg-2" for="score3">Match 3</label>
                </div>
                <!--                DEBUT MATCH DOUBLE-->
                <?php $i=0;
                /** @var DoubleModel $double */
                foreach ($_allDouble as $double):
                    $i++;?>
                    <div class="row marginBtm" align="center" id="double[<?php echo $i ?>]">
                        <div class="col-lg-2 col-sm-5">
                            <select title="double1_1" class="form-control form-control2 first" id="joueurD1_1[<?php echo $i ?>]" name="joueurD[<?php echo $i ?>][joueur_1_1]">
                                <option value="0"></option>
                            <?php /** @var JoueurModel $joueur */
                            foreach ($joueurs_1 as $joueur) : ?>
                                <option value="<?php echo $joueur->getAttribute('id') ?>" <?php echo $double->getAttribute('joueur_1_1')==$joueur->getAttribute('id')?'selected':'' ?>><?php echo $joueur->getAttribute('name') ?></option>
                            <?php endforeach; ?>
                            </select>
                            <select title="double1_2" class="form-control form-control2 first" id="joueurD2_1[<?php echo $i ?>]" name="joueurD[<?php echo $i ?>][joueur_1_2]">
                                <option value="0"></option>
                            <?php /** @var JoueurModel $joueur */
                            foreach ($joueurs_1 as $joueur) : ?>
                                <option value="<?php echo $joueur->getAttribute('id') ?>" <?php echo $double->getAttribute('joueur_1_2')==$joueur->getAttribute('id')?'selected':'' ?>><?php echo $joueur->getAttribute('name') ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-lg-2 col-sm-5">
                            <select title="double2_1" class="form-control form-control2 second" id="joueurD1_2[<?php echo $i ?>]" name="joueurD[<?php echo $i ?>][joueur_2_1]">
                                <option value="0"></option>
                                <?php /** @var JoueurModel $joueur */
                                foreach ($joueurs_2 as $joueur) : ?>
                                    <option value="<?php echo $joueur->getAttribute('id') ?>" <?php echo $double->getAttribute('joueur_2_1')==$joueur->getAttribute('id')?'selected':'' ?>><?php echo $joueur->getAttribute('name') ?></option>
                                <?php endforeach; ?>
                            </select>
                            <select title="double2_2" class="form-control form-control2 second" id="joueurD2_2[<?php echo $i ?>]" name="joueurD[<?php echo $i ?>][joueur_2_2]">
                                <option value="0"></option>
                                <?php /** @var JoueurModel $joueur */
                                foreach ($joueurs_2 as $joueur) : ?>
                                    <option value="<?php echo $joueur->getAttribute('id') ?>" <?php echo $double->getAttribute('joueur_2_2')==$joueur->getAttribute('id')?'selected':'' ?>><?php echo $joueur->getAttribute('name') ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-lg-2 col-sm-10">
                            <input class="form-control first" id="scoreD1_1[<?php echo $i ?>]" type="number" value="<?php echo $double->getAttribute('score_1_1') ?>" name="scoreD[<?php echo $i ?>][match_1_1]">
                            <input class="form-control second" id="scoreD1_2[<?php echo $i ?>]" type="number" value="<?php echo $double->getAttribute('score_1_2') ?>" name="scoreD[<?php echo $i ?>][match_1_2]">
                        </div>
                        <div class="col-lg-2 col-sm-10">
                            <input class="form-control btn-xs first" id="scoreD2_1[<?php echo $i ?>]" type="number" value="<?php echo $double->getAttribute('score_2_1') ?>" name="scoreD[<?php echo $i ?>][match_2_1]">
                            <input class="form-control btn-xs second" id="scoreD2_2[<?php echo $i ?>]" type="number" value="<?php echo $double->getAttribute('score_2_2') ?>" name="scoreD[<?php echo $i ?>][match_2_2]">
                        </div>
                        <div class="col-lg-2 col-sm-10">
                            <input class="form-control btn-xs first" id="scoreD3_1[<?php echo $i ?>]" type="number" value="<?php echo $double->getAttribute('score_3_1') ?>" name="scoreD[<?php echo $i ?>][match_3_1]">
                            <input class="form-control btn-xs second" id="scoreD3_2[<?php echo $i ?>]" type="number" value="<?php echo $double->getAttribute('score_3_2') ?>" name="scoreD[<?php echo $i ?>][match_3_2]">
                        </div>
                        <div class="col-lg-1">
                            <p class="score_binaire"></p>
                        </div>
                        <div class="col-lg-1">
                            <button class="btn btn-default red" type="button" data-idD="<?php echo $i ?>">-</button>
                        </div>
                        <input type="hidden" name="databaseIdD[<?php echo $i ?>]" value="<?php echo $double->getAttribute('id')?>">
                    </div>
                <?php endforeach;?>
                <!--                FIN MATCH DOUBLE-->
            </div>
        </div>
    </form>
</div>
