<?php
/**
 * Created by PhpStorm.
 * User: corentin
 * Date: 19/07/16
 * Time: 21:19
 */

/** @var StatistiquesController $_statistiques */
$_statistiques = $this;

$limit = 2;

$winLoseSimpleDom = $_statistiques->getWinLoseSimpleDom(true);
$winLoseSimpleExt = $_statistiques->getWinLoseSimpleExt(true);
$winLoseSimpleAll = $_statistiques->getWinLoseSimpleAll($_statistiques->getWinLoseSimpleDom(), $_statistiques->getWinLoseSimpleExt());
$highestPointSimple = $_statistiques->getHighestPointSimple(true);
$winLoseDoubleDom = $_statistiques->getWinLoseDoubleDom(true);
$winLoseDoubleExt = $_statistiques->getWinLoseDoubleExt(true);
$winLoseDoubleAll = $_statistiques->getWinLoseDoubleAll($_statistiques->getWinLoseDoubleDom(), $_statistiques->getWinLoseDoubleExt());
$highestPointDouble = $_statistiques->getHighestPointDouble(true);
?>
<div align="center">

    <!-- DEBUT STAT -->

<?php if(sizeof($winLoseSimpleAll) >= $limit): ?>
    <div class="row" style="margin-top: 15px;">
        <h4 class="stat_header">Classement des joueurs en simple (victoire / matchs joués)</h4>
        <div style="margin-top: 25px;">
<?php
$i = 0;
foreach ($winLoseSimpleAll as $key => $value):
    if($i > 2)
        break;
?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p><?php echo $value['nom'] ?> (<?php echo $value['equipe'] ?>)</p>
        <div class="c100 p<?php echo $value['ratio'] ?> small">
            <span><?php echo $value['ratio'] ?>%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoires <?php echo $value['win'] ?>/<?php echo $value['total']?> matchs</p>
    </div>
<?php
    $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
<?php
    $i++;
endwhile;
?>
        </div>
    </div>

    <!-- FIN STAT -->
    <!-- DEBUT STAT -->

<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
        <?php if(sizeof($winLoseSimpleDom) >= $limit): ?>
        <h4 class="stat_header">Classement des joueurs en simple à domicile (victoire / matchs joués)</h4>
            <div style="margin-top: 25px;">
<?php
$i = 0;
foreach ($winLoseSimpleDom as $key => $value):
    if($i > 2)
        break;
?>
        <div class="col-lg-4">
            <p><b><?php echo $i+1 ?></b></p>
            <p><?php echo $value['nom'] ?> (<?php echo $value['equipe'] ?>)</p>
            <div class="c100 p<?php echo $value['ratio'] ?> small">
                <span><?php echo $value['ratio'] ?>%</span>
                <div class="slice">
                    <div class="bar"></div>
                    <div class="fill"></div>
                </div>
            </div>
            <p>victoires <?php echo $value['win'] ?>/<?php echo $value['total']?> matchs</p>
        </div>
<?php $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
<?php
    $i++;
endwhile;
?>
        </div>
    </div>
<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
<?php if(sizeof($winLoseSimpleExt) >= $limit): ?>
        <h4 class="stat_header">Classement des joueurs en simple à l'extérieur (victoire / matchs joués)</h4>
        <div style="margin-top: 25px;">
        <?php
$i = 0;
foreach ($winLoseSimpleExt as $key => $value):
    if($i > 2)
        break;
?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p><?php echo $value['nom'] ?> (<?php echo $value['equipe'] ?>)</p>
        <div class="c100 p<?php echo $value['ratio'] ?> small">
            <span><?php echo $value['ratio'] ?>%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoires <?php echo $value['win'] ?>/<?php echo $value['total']?> matchs</p>
    </div>
<?php
    $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
<?php
    $i++;
endwhile;
?>
        </div>
    </div>
<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
<?php if(sizeof($highestPointSimple) >= $limit):
        ?>
        <h4 class="stat_header">Classement des joueurs ayant marqué le plus de point par sets en simple (points / sets joués)</h4>
        <div style="margin-top: 25px;">
<?php
$i = 0;
foreach ($highestPointSimple as $key => $value):
    if($i > 2)
        break;
    ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p><?php echo $value['nom'] ?> (<?php echo $value['equipe'] ?>)</p>
        <div class="c100 p100 small orange">
            <span><?php echo $value['ratio'] ?>pts</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>points <?php echo $value['sum'] ?>/<?php echo $value['total']?> sets</p>
    </div>
    <?php
    $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
    <?php
    $i++;
endwhile;
?>
        </div>
    </div>
<?php endif; ?>
<?php if(sizeof($winLoseDoubleAll) >= $limit): ?>
    <div class="row" style="margin-top: 15px;">
        <h4 class="stat_header">Classement des meilleurs duos (victoire / matchs joués)</h4>
        <div style="margin-top: 25px;">
<?php
$i = 0;
foreach ($winLoseDoubleAll as $key => $value):
    if($i > 2)
        break;
?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p><?php echo $value['joueur1'] ?> et <?php echo $value['joueur2'] ?> (<?php echo $value['equipe'] ?>)</p>
        <div class="c100 p<?php echo $value['ratio'] ?> small">
            <span><?php echo $value['ratio'] ?>%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoires <?php echo $value['sup'] ?>/<?php echo $value['total']?> matchs</p>
    </div>
<?php
    $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
<?php
    $i++;
endwhile;
?>
        </div>
    </div>

    <!-- FIN STAT -->
    <!-- DEBUT STAT -->

<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
        <?php if(sizeof($winLoseDoubleDom) >= $limit): ?>
        <h4 class="stat_header">Classement des meilleurs duos à domicile (victoire / matchs joués)</h4>
            <div style="margin-top: 25px;">
<?php
$i = 0;
foreach ($winLoseDoubleDom as $key => $value):
    if($i > 2)
        break;
?>
        <div class="col-lg-4">
            <p><b><?php echo $i+1 ?></b></p>
            <p><?php echo $value['joueur1'] ?> et <?php echo $value['joueur2'] ?> (<?php echo $value['equipe'] ?>)</p>
            <div class="c100 p<?php echo $value['ratio'] ?> small">
                <span><?php echo $value['ratio'] ?>%</span>
                <div class="slice">
                    <div class="bar"></div>
                    <div class="fill"></div>
                </div>
            </div>
            <p>victoires <?php echo $value['sup'] ?>/<?php echo $value['total']?> matchs</p>
        </div>
<?php $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
<?php
    $i++;
endwhile;
?>
        </div>
    </div>
<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
<?php if(sizeof($winLoseDoubleExt) >= $limit): ?>
        <h4 class="stat_header">Classement des meilleurs duos à l'extérieur (victoire / matchs joués)</h4>
        <div style="margin-top: 25px;">
        <?php
$i = 0;
foreach ($winLoseDoubleExt as $key => $value):
    if($i > 2)
        break;
?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p><?php echo $value['joueur1'] ?> et <?php echo $value['joueur2'] ?> (<?php echo $value['equipe'] ?>)</p>
        <div class="c100 p<?php echo $value['ratio'] ?> small">
            <span><?php echo $value['ratio'] ?>%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoires <?php echo $value['sup'] ?>/<?php echo $value['total']?> matchs</p>
    </div>
<?php
    $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
<?php
    $i++;
endwhile;
?>
        </div>
    </div>
<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
<?php if(sizeof($highestPointSimple) >= $limit):
        ?>
        <h4 class="stat_header">Classement des dus ayant marqué le plus de point par sets en double (points / sets joués)</h4>
        <div style="margin-top: 25px;">
<?php
$i = 0;
foreach ($highestPointDouble as $key => $value):
    if($i > 2)
        break;
    ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p><?php echo $value['joueur1'] ?> et <?php echo $value['joueur2'] ?> (<?php echo $value['equipe'] ?>)</p>
        <div class="c100 p100 small orange">
            <span><?php echo $value['ratio'] ?>pts</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>points <?php echo $value['sum'] ?>/<?php echo $value['total']?> sets</p>
    </div>
    <?php
    $i++;
endforeach;
while($i <= 2): ?>
    <div class="col-lg-4">
        <p><b><?php echo $i+1 ?></b></p>
        <p>Personne</p>
        <div class="c100 p0 small">
            <span>0%</span>
            <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
            </div>
        </div>
        <p>victoire 0/0 match</p>
    </div>
    <?php
    $i++;
endwhile;
?>
        </div>
    </div>
<?php endif; ?>
</div>
