<?php
/**
 * Created by PhpStorm.
 * User: corentin
 * Date: 19/07/16
 * Time: 21:19
 */

/** @var StatistiquesController $_statistiques */
$_statistiques = $this;

$limit = 2;

$winLoseSimpleDom = $_statistiques->getWinLoseSimpleDom(true);
$winLoseSimpleExt = $_statistiques->getWinLoseSimpleExt(true);
$winLoseSimpleAll = $_statistiques->getWinLoseSimpleAll($_statistiques->getWinLoseSimpleDom(), $_statistiques->getWinLoseSimpleExt());
$highestPointSimple = $_statistiques->getHighestPointSimple(true);
$winLoseDoubleDom = $_statistiques->getWinLoseDoubleDom(true);
$winLoseDoubleExt = $_statistiques->getWinLoseDoubleExt(true);
$winLoseDoubleAll = $_statistiques->getWinLoseDoubleAll($_statistiques->getWinLoseDoubleDom(), $_statistiques->getWinLoseDoubleExt());
$highestPointDouble = $_statistiques->getHighestPointDouble(true);
?>
<div align="center">
    <ul>
        <?php if(sizeof($winLoseSimpleAll) >= $limit): ?>
        <li class="marginBtmBig"><h4>Classement des joueurs en simple (victoire / matchs joués)</h4>
            <ul>
<?php
$i = 0;
foreach ($winLoseSimpleAll as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['nom']} ({$value['equipe']}) : {$value['ratio']}% de victoires ({$value['win']}/{$value['total']})</li>";
    $i++;
}

?>
            </ul>
        </li>
        <?php endif;
        if(sizeof($winLoseSimpleDom) >= $limit):
        ?>
        <li class="marginBtmBig"><h4>Classement des joueurs en simple à domicile (victoire / matchs joués)</h4>
            <ul>
<?php
$i = 0;
foreach ($winLoseSimpleDom as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['nom']} ({$value['equipe']}) : {$value['ratio']}% de victoires ({$value['win']}/{$value['total']})</li>";
    $i++;
}

?>
            </ul>
        </li>
        <?php endif;
        if(sizeof($winLoseSimpleExt) >= $limit):
        ?>
        <li class="marginBtmBig"><h4>Classement des joueurs en simple à l'extérieur (victoire / matchs joués)</h4>
            <ul>
<?php

$i = 0;
foreach ($winLoseSimpleExt as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['nom']} ({$value['equipe']}) : {$value['ratio']}% de victoires ({$value['win']}/{$value['total']})</li>";
    $i++;
}
?>
            </ul>
        </li>
        <?php endif;
        if(sizeof($highestPointSimple) >= $limit):
        ?>
        <li class="marginBtmBig"><h4>Classement des joueurs ayant marqué le plus de point par sets en simple (points / sets joués)</h4>
            <ul>
<?php

$i = 0;
foreach ($highestPointSimple as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['nom']} ({$value['equipe']}) : {$value['ratio']} points par match ({$value['sum']}/{$value['total']})</li>";
    $i++;
}
?>
            </ul>
        </li>
        <?php endif;
        if(sizeof($winLoseDoubleAll) >= $limit): ?>
            <li class="marginBtmBig"><h4>Classement des duos (victoire / matchs joués)</h4>
                <ul>
                    <?php
                    $i = 0;
                    foreach ($winLoseDoubleAll as $key => $value) {
                        if($i > 2) {
                            break;
                        }
                        echo "<li>{$value['joueur1']} et {$value['joueur2']} ({$value['equipe']}) : {$value['ratio']}% victoires ({$value['sup']}/{$value['total']})</li>";
                        $i++;
                    }

                    ?>
                </ul>
            </li>
        <?php endif;
        if(sizeof($winLoseDoubleDom) >= $limit):
        ?>
        <li class="marginBtmBig"><h4>Classement des duos à domicile (victoires / matchs joués)</h4>
            <ul>
<?php

$i = 0;
foreach ($winLoseDoubleDom as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['joueur1']} et {$value['joueur2']} ({$value['equipe']}) : {$value['ratio']}% de victoires ({$value['sup']}/{$value['total']})</li>";
    $i++;
}
?>
            </ul>
        </li>
        <?php endif;
        if(sizeof($winLoseDoubleExt) >= $limit):
        ?>
        <li class="marginBtmBig"><h4>Classement des duos à l'extérieur (victoires / matchs joués)</h4>
            <ul>
<?php

$i = 0;
foreach ($winLoseDoubleExt as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['joueur1']} et {$value['joueur2']} ({$value['equipe']}) : {$value['ratio']}% de victoires ({$value['sup']}/{$value['total']})</li>";
    $i++;
}
?>
            </ul>
        </li>
        <?php endif;
        if(sizeof($highestPointDouble) >= $limit):
        ?>
        <li class="marginBtmBig"><h4>Classement des duos ayant marqué le plus de point par sets en double (points / sets joués)</h4>
            <ul>
<?php

$i = 0;
foreach ($highestPointDouble as $key => $value) {
    if($i > 2) {
        break;
    }
    echo "<li>{$value['joueur1']} et {$value['joueur2']} ({$value['equipe']}) : {$value['ratio']} points par match ({$value['sum']}/{$value['total']})</li>";
    $i++;
}
?>
            </ul>
        </li>
        <?php endif; ?>
    </ul>
</div>
