<?php
/**
 * Created by PhpStorm.
 * User: corentin
 * Date: 19/07/16
 * Time: 21:19
 */

/** @var StatistiquesController $_statistiques */
$_statistiques = $this;

$limit = ReadIni::getInstance()->getAttribute('general', 'statlim');

$winLoseSimpleDom = $_statistiques->getWinLoseSimpleDom(true);
$winLoseSimpleExt = $_statistiques->getWinLoseSimpleExt(true);
$winLoseSimpleAll = $_statistiques->getWinLoseSimpleAll($_statistiques->getWinLoseSimpleDom(), $_statistiques->getWinLoseSimpleExt());
$highestPointSimple = $_statistiques->getHighestPointSimple(true);
$winLoseDoubleDom = $_statistiques->getWinLoseDoubleDom(true);
$winLoseDoubleExt = $_statistiques->getWinLoseDoubleExt(true);
$winLoseDoubleAll = $_statistiques->getWinLoseDoubleAll($_statistiques->getWinLoseDoubleDom(), $_statistiques->getWinLoseDoubleExt());
$highestPointDouble = $_statistiques->getHighestPointDouble(true);
?>
<div align="center">

    <!-- DEBUT STAT -->

<?php if(sizeof($winLoseSimpleAll) >= $limit): ?>
    <div class="row" style="margin-top: 15px;">
        <h4 class="stat_header">Victoires en simple (victoire / matchs joués)</h4>
        <div style="margin-top: 25px;" class="col-lg-offset-2 col-lg-8">
            <table class="table table-hover" style="table-layout: fixed">
                <tr>
                    <th colspan="1">N°</th>
                    <th colspan="3">Joueur</th>
                    <th colspan="3">Equipe</th>
                    <th colspan="2">% Victoire</th>
                    <th colspan="2">Gagnés</th>
                    <th colspan="2">Joués</th>
                </tr>

<?php
$i = 0;
foreach ($winLoseSimpleAll as $key => $value):
    if($i > $limit)
        break;
?>
                <tr>
                    <td colspan="1"><?php echo $i+1 ?></td>
                    <td colspan="3"><?php echo $value['nom'] ?></td>
                    <td colspan="3"><?php echo $value['equipe'] ?></td>
                    <td colspan="2"><?php echo $value['ratio'] ?> %</td>
                    <td colspan="2"><?php echo $value['win'] ?> V</td>
                    <td colspan="2"><?php echo $value['total']?> J</td>
                </tr>
<?php
    $i++;
endforeach; ?>
            </table>
        </div>
    </div>

    <!-- FIN STAT -->
<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
<?php if(sizeof($highestPointSimple) >= $limit):
        ?>
        <h4 class="stat_header">Points par sets en simple (points / sets joués)</h4>
        <div style="margin-top: 25px;" class="col-lg-offset-2 col-lg-8">
            <table class="table table-hover" style="table-layout: fixed">
                <tr>
                    <th colspan="1">N°</th>
                    <th colspan="3">Joueur</th>
                    <th colspan="3">Equipe</th>
                    <th colspan="2">Points / Sets</th>
                    <th colspan="2">Points</th>
                    <th colspan="2">Sets</th>
                </tr>

                    <?php
                    $i = 0;
                    foreach ($highestPointSimple as $key => $value):
                        if($i > $limit)
                            break;
                        ?>
                <tr>
                    <td colspan="1"><?php echo $i+1 ?></td>
                    <td colspan="3"><?php echo $value['nom'] ?></td>
                    <td colspan="3"><?php echo $value['equipe'] ?></td>
                    <td colspan="2"><?php echo $value['ratio'] ?> pts/set</td>
                    <td colspan="2"><?php echo $value['sum'] ?> pts</td>
                    <td colspan="2"><?php echo $value['total']?> sets</td>
                </tr>
                        <?php
                        $i++;
                    endforeach; ?>
            </table>
        </div>
    </div>
<?php endif; ?>
<?php if(sizeof($winLoseDoubleAll) >= $limit): ?>
    <div class="row" style="margin-top: 15px;">
        <h4 class="stat_header">Victoires en double (victoire / matchs joués)</h4>
        <div style="margin-top: 25px;" class="col-lg-offset-2 col-lg-8">
            <table class="table table-hover" style="table-layout: fixed">
                <tr>
                    <th colspan="1">N°</th>
                    <th colspan="3">Joueurs</th>
                    <th colspan="3">Equipe</th>
                    <th colspan="2">% Victoire</th>
                    <th colspan="2">Gagnés</th>
                    <th colspan="2">Joués</th>
                </tr>

<?php
$i = 0;
foreach ($winLoseDoubleAll as $key => $value):
    if($i > $limit)
        break;
?>
                <tr>
                    <td colspan="1"><?php echo $i+1 ?></td>
                    <td colspan="3"><?php echo $value['joueur1'].' & '.$value['joueur2'] ?></td>
                    <td colspan="3"><?php echo $value['equipe'] ?></td>
                    <td colspan="2"><?php echo $value['ratio'] ?> %</td>
                    <td colspan="2"><?php echo $value['sup'] ?> V</td>
                    <td colspan="2"><?php echo $value['total']?> J</td>
                </tr>
<?php
    $i++;
endforeach; ?>
            </table>
        </div>
    </div>

    <!-- FIN STAT -->
<?php endif; ?>
    <div class="row" style="margin-top: 15px;">
<?php if(sizeof($highestPointSimple) >= $limit):
        ?>
        <h4 class="stat_header">Points par sets en double (points / sets joués)</h4>
        <div style="margin-top: 25px;" class="col-lg-offset-2 col-lg-8">
            <table class="table table-hover" style="table-layout: fixed">
                <tr>
                    <th colspan="1">N°</th>
                    <th colspan="3">Joueurs</th>
                    <th colspan="3">Equipe</th>
                    <th colspan="2">Points / Sets</th>
                    <th colspan="2">Points</th>
                    <th colspan="2">Sets</th>
                </tr>
                    <?php
                    $i = 0;
                    foreach ($highestPointSimple as $key => $value):
                        if($i > $limit)
                            break;
                        ?>
                <tr>
                    <td colspan="1"><?php echo $i+1 ?></td>
                    <td colspan="3"><?php echo $value['joueur1'] . ' & '  . $value['joueur2'] ?></td>
                    <td colspan="3"><?php echo $value['equipe'] ?></td>
                    <td colspan="2"><?php echo $value['ratio'] ?> pts/set</td>
                    <td colspan="2"><?php echo $value['sum'] ?> pts</td>
                    <td colspan="2"><?php echo $value['total']?> sets</td>
                </tr>
                        <?php
                        $i++;
                    endforeach; ?>
            </table>
        </div>
    </div>
<?php endif; ?>
</div>
