<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 04/05/16
 * Time: 16:57
 */
/** @var AdminController $_admin */
$_admin = $this;
$_allEquipe = $_admin->getAllEquipe();
?>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nouveau Match</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" action="<?php echo $_admin->getUrlAction('addMatch'); ?>" method="POST">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="ronde" class="col-sm-4 control-label">Ronde</label>
                                <div class="col-sm-4">
                                    <input type="number" class="form-control2 form-control" id="ronde" name="ronde">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mrg-bottom">
                        <div class="col-xs-5 col-lg-5">
                            <select name="equipe_id_1" class="form-control2 form-control">
                                <?php /** @var EquipeModel $_equipe */ ?>
                                <?php foreach ($_allEquipe as $_equipe): ?>
                                    <option value="<?php echo $_equipe->getAttribute('id') ?>"><?php echo $_equipe->getAttribute("name") ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-xs-2 col-lg-2 center">
                            vs
                        </div>
                        <div class="col-xs-5 col-lg-5">
                            <select name="equipe_id_2" class="form-control2 form-control">
                                <?php /** @var EquipeModel $_equipe */ ?>
                                <?php foreach ($_allEquipe as $_equipe): ?>
                                    <option value="<?php echo $_equipe->getAttribute('id') ?>"><?php echo $_equipe->getAttribute("name") ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="submit" class="btn btn-default">Enregistrer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
