<?php
/** @var AdminController $_admin */
$_admin = $this;
$_allEquipe = $_admin->getAllEquipe();
?>
<div class="row">
    <p class="col-lg-12" id="info"></p>
</div>
<div class="row">
    <div class="col-lg-5 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Terminer le tournoi en cours</h3>
            </div>
            <div class="panel-body col-lg-offset-1">
                <div class="row">
                    <button id="endTournament" class="btn btn-danger">Cloturer le tournoi en cours</button>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nouveau tournoi</h3>
            </div>
            <div class="panel-body col-lg-offset-1">
                <div class="row">
                    <form action="<?php echo $_admin->getUrlAction('createTournament'); ?>" method="POST">
                        <div class="row">
                            <label for='equipes'>Sélection des équipes </label>
                        </div>
                        <div class="row">
                            <select multiple size="15" class="form-control" id='equipes' name="equipes[]">
                            <?php
                            /** @var EquipeModel $equipe */
                            foreach ($_allEquipe as $equipe): ?>
                                <option value="<?php echo $equipe->getAttribute('id') ?>"><?php echo $equipe->getAttribute('name') ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="row">
                            <input type="submit" class="btn btn-default" value="Créer le tournoi">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Attention : clotûre tournoi</h4>
            </div>
            <div class="modal-body">
                <p>Êtes-vous sur de vouloir fermer le tournois en cours ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <form action="<?php echo $_admin->getUrlAction('closeTournament'); ?>" method="POST">
                    <input type="submit" class="btn btn-primary modalValidate" value="Valider">
                </form>
            </div>
        </div>
    </div>
</div>